version: '3'
services:
  web:
    build: "./../exemplo_1/"
    container_name: treinamento_lead
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - postgres-compose-network
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "lead"
    volumes:
      - ./../exemplo_2/init_scripts/init_teste.sql:/docker-entrypoint-initdb.d/init.sql
      - ./../exemplo_2/volumes_example:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
       PGADMIN_DEFAULT_EMAIL: "a@b.com.br"
       PGADMIN_DEFAULT_PASSWORD: "lead"
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network
      
  airflow_lead:
    container_name: airflow_lead
    image: puckel/docker-airflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags/:/usr/local/airflow/dags
      - ./airflow/datalake/:/usr/local/airflow/datalake
    networks:
      - postgres-compose-network

  mongo:
    container_name: mongo_treinamento_lead
    image: mongo
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: lead
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - postgres-compose-network

  mongo-express:
    container_name: mongo_express_treinamento_lead
    image: mongo-express
    restart: "always"
    ports:
      - "8084:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: lead
      ME_CONFIG_BASICAUTH_PASSWORD: lead
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: lead
    depends_on:
      - mongo
    networks:
      - postgres-compose-network

  metabase:
    image: metabase/metabase
    container_name: metabase_treinamento
    restart: "always"
    ports:
      - "3001:3000"
    volumes:
      - ./metabase-data/:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: lead
      MB_DB_HOST: db
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge