version: '3'
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "lead"
    volumes:
      - ./init_scripts/init_teste.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes_example:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
       PGADMIN_DEFAULT_EMAIL: "a@b.com.br"
       PGADMIN_DEFAULT_PASSWORD: "lead"
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge